// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/list_prime.proto

package primeser

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InputNum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           int32                  `protobuf:"varint,1,opt,name=Num,proto3" json:"Num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputNum) Reset() {
	*x = InputNum{}
	mi := &file_proto_list_prime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputNum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputNum) ProtoMessage() {}

func (x *InputNum) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_prime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputNum.ProtoReflect.Descriptor instead.
func (*InputNum) Descriptor() ([]byte, []int) {
	return file_proto_list_prime_proto_rawDescGZIP(), []int{0}
}

func (x *InputNum) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type OutputList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrimesList    []int32                `protobuf:"varint,1,rep,packed,name=PrimesList,proto3" json:"PrimesList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputList) Reset() {
	*x = OutputList{}
	mi := &file_proto_list_prime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputList) ProtoMessage() {}

func (x *OutputList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_prime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputList.ProtoReflect.Descriptor instead.
func (*OutputList) Descriptor() ([]byte, []int) {
	return file_proto_list_prime_proto_rawDescGZIP(), []int{1}
}

func (x *OutputList) GetPrimesList() []int32 {
	if x != nil {
		return x.PrimesList
	}
	return nil
}

type OutputResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsPrime       string                 `protobuf:"bytes,1,opt,name=isPrime,proto3" json:"isPrime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputResult) Reset() {
	*x = OutputResult{}
	mi := &file_proto_list_prime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputResult) ProtoMessage() {}

func (x *OutputResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_list_prime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputResult.ProtoReflect.Descriptor instead.
func (*OutputResult) Descriptor() ([]byte, []int) {
	return file_proto_list_prime_proto_rawDescGZIP(), []int{2}
}

func (x *OutputResult) GetIsPrime() string {
	if x != nil {
		return x.IsPrime
	}
	return ""
}

var File_proto_list_prime_proto protoreflect.FileDescriptor

const file_proto_list_prime_proto_rawDesc = "" +
	"\n" +
	"\x16proto/list_prime.proto\"\x1c\n" +
	"\bInputNum\x12\x10\n" +
	"\x03Num\x18\x01 \x01(\x05R\x03Num\",\n" +
	"\n" +
	"OutputList\x12\x1e\n" +
	"\n" +
	"PrimesList\x18\x01 \x03(\x05R\n" +
	"PrimesList\"(\n" +
	"\fOutputResult\x12\x18\n" +
	"\aisPrime\x18\x01 \x01(\tR\aisPrime2\\\n" +
	"\fPrimeService\x12$\n" +
	"\n" +
	"ListPrimes\x12\t.InputNum\x1a\v.OutputList\x12&\n" +
	"\n" +
	"CheckPrime\x12\t.InputNum\x1a\r.OutputResultB Z\x1edist_scheduler/proto/;primeserb\x06proto3"

var (
	file_proto_list_prime_proto_rawDescOnce sync.Once
	file_proto_list_prime_proto_rawDescData []byte
)

func file_proto_list_prime_proto_rawDescGZIP() []byte {
	file_proto_list_prime_proto_rawDescOnce.Do(func() {
		file_proto_list_prime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_list_prime_proto_rawDesc), len(file_proto_list_prime_proto_rawDesc)))
	})
	return file_proto_list_prime_proto_rawDescData
}

var file_proto_list_prime_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_list_prime_proto_goTypes = []any{
	(*InputNum)(nil),     // 0: InputNum
	(*OutputList)(nil),   // 1: OutputList
	(*OutputResult)(nil), // 2: OutputResult
}
var file_proto_list_prime_proto_depIdxs = []int32{
	0, // 0: PrimeService.ListPrimes:input_type -> InputNum
	0, // 1: PrimeService.CheckPrime:input_type -> InputNum
	1, // 2: PrimeService.ListPrimes:output_type -> OutputList
	2, // 3: PrimeService.CheckPrime:output_type -> OutputResult
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_list_prime_proto_init() }
func file_proto_list_prime_proto_init() {
	if File_proto_list_prime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_list_prime_proto_rawDesc), len(file_proto_list_prime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_list_prime_proto_goTypes,
		DependencyIndexes: file_proto_list_prime_proto_depIdxs,
		MessageInfos:      file_proto_list_prime_proto_msgTypes,
	}.Build()
	File_proto_list_prime_proto = out.File
	file_proto_list_prime_proto_goTypes = nil
	file_proto_list_prime_proto_depIdxs = nil
}
