// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/list_prime.proto

package primeser

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PrimeService_ListPrimes_FullMethodName = "/PrimeService/ListPrimes"
	PrimeService_CheckPrime_FullMethodName = "/PrimeService/CheckPrime"
)

// PrimeServiceClient is the client API for PrimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrimeServiceClient interface {
	ListPrimes(ctx context.Context, in *InputNum, opts ...grpc.CallOption) (*OutputList, error)
	CheckPrime(ctx context.Context, in *InputNum, opts ...grpc.CallOption) (*OutputResult, error)
}

type primeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrimeServiceClient(cc grpc.ClientConnInterface) PrimeServiceClient {
	return &primeServiceClient{cc}
}

func (c *primeServiceClient) ListPrimes(ctx context.Context, in *InputNum, opts ...grpc.CallOption) (*OutputList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OutputList)
	err := c.cc.Invoke(ctx, PrimeService_ListPrimes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *primeServiceClient) CheckPrime(ctx context.Context, in *InputNum, opts ...grpc.CallOption) (*OutputResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OutputResult)
	err := c.cc.Invoke(ctx, PrimeService_CheckPrime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrimeServiceServer is the server API for PrimeService service.
// All implementations must embed UnimplementedPrimeServiceServer
// for forward compatibility.
type PrimeServiceServer interface {
	ListPrimes(context.Context, *InputNum) (*OutputList, error)
	CheckPrime(context.Context, *InputNum) (*OutputResult, error)
	mustEmbedUnimplementedPrimeServiceServer()
}

// UnimplementedPrimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrimeServiceServer struct{}

func (UnimplementedPrimeServiceServer) ListPrimes(context.Context, *InputNum) (*OutputList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPrimes not implemented")
}
func (UnimplementedPrimeServiceServer) CheckPrime(context.Context, *InputNum) (*OutputResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPrime not implemented")
}
func (UnimplementedPrimeServiceServer) mustEmbedUnimplementedPrimeServiceServer() {}
func (UnimplementedPrimeServiceServer) testEmbeddedByValue()                      {}

// UnsafePrimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrimeServiceServer will
// result in compilation errors.
type UnsafePrimeServiceServer interface {
	mustEmbedUnimplementedPrimeServiceServer()
}

func RegisterPrimeServiceServer(s grpc.ServiceRegistrar, srv PrimeServiceServer) {
	// If the following call pancis, it indicates UnimplementedPrimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PrimeService_ServiceDesc, srv)
}

func _PrimeService_ListPrimes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputNum)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrimeServiceServer).ListPrimes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrimeService_ListPrimes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrimeServiceServer).ListPrimes(ctx, req.(*InputNum))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrimeService_CheckPrime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputNum)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrimeServiceServer).CheckPrime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrimeService_CheckPrime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrimeServiceServer).CheckPrime(ctx, req.(*InputNum))
	}
	return interceptor(ctx, in, info, handler)
}

// PrimeService_ServiceDesc is the grpc.ServiceDesc for PrimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PrimeService",
	HandlerType: (*PrimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPrimes",
			Handler:    _PrimeService_ListPrimes_Handler,
		},
		{
			MethodName: "CheckPrime",
			Handler:    _PrimeService_CheckPrime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/list_prime.proto",
}
