// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/scheduler.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrimeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           int32                  `protobuf:"varint,1,opt,name=Num,proto3" json:"Num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrimeReq) Reset() {
	*x = PrimeReq{}
	mi := &file_proto_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrimeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeReq) ProtoMessage() {}

func (x *PrimeReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeReq.ProtoReflect.Descriptor instead.
func (*PrimeReq) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *PrimeReq) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type PrimeRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrimeList     []int32                `protobuf:"varint,1,rep,packed,name=PrimeList,proto3" json:"PrimeList,omitempty"`
	ProcessedBy   int32                  `protobuf:"varint,2,opt,name=ProcessedBy,proto3" json:"ProcessedBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrimeRes) Reset() {
	*x = PrimeRes{}
	mi := &file_proto_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrimeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimeRes) ProtoMessage() {}

func (x *PrimeRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrimeRes.ProtoReflect.Descriptor instead.
func (*PrimeRes) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *PrimeRes) GetPrimeList() []int32 {
	if x != nil {
		return x.PrimeList
	}
	return nil
}

func (x *PrimeRes) GetProcessedBy() int32 {
	if x != nil {
		return x.ProcessedBy
	}
	return 0
}

type HeartbeatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerID      int32                  `protobuf:"varint,1,opt,name=WorkerID,proto3" json:"WorkerID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatReq) Reset() {
	*x = HeartbeatReq{}
	mi := &file_proto_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReq) ProtoMessage() {}

func (x *HeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReq.ProtoReflect.Descriptor instead.
func (*HeartbeatReq) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatReq) GetWorkerID() int32 {
	if x != nil {
		return x.WorkerID
	}
	return 0
}

type HeartbeatRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAlive       bool                   `protobuf:"varint,1,opt,name=IsAlive,proto3" json:"IsAlive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRes) Reset() {
	*x = HeartbeatRes{}
	mi := &file_proto_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRes) ProtoMessage() {}

func (x *HeartbeatRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRes.ProtoReflect.Descriptor instead.
func (*HeartbeatRes) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRes) GetIsAlive() bool {
	if x != nil {
		return x.IsAlive
	}
	return false
}

var File_proto_scheduler_proto protoreflect.FileDescriptor

const file_proto_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x15proto/scheduler.proto\"\x1c\n" +
	"\bPrimeReq\x12\x10\n" +
	"\x03Num\x18\x01 \x01(\x05R\x03Num\"J\n" +
	"\bPrimeRes\x12\x1c\n" +
	"\tPrimeList\x18\x01 \x03(\x05R\tPrimeList\x12 \n" +
	"\vProcessedBy\x18\x02 \x01(\x05R\vProcessedBy\"*\n" +
	"\fHeartbeatReq\x12\x1a\n" +
	"\bWorkerID\x18\x01 \x01(\x05R\bWorkerID\"(\n" +
	"\fHeartbeatRes\x12\x18\n" +
	"\aIsAlive\x18\x01 \x01(\bR\aIsAlive2/\n" +
	"\tScheduler\x12\"\n" +
	"\n" +
	"ListPrimes\x12\t.PrimeReq\x1a\t.PrimeRes2W\n" +
	"\x06Worker\x12\"\n" +
	"\n" +
	"ListPrimes\x12\t.PrimeReq\x1a\t.PrimeRes\x12)\n" +
	"\tHeartbeat\x12\r.HeartbeatReq\x1a\r.HeartbeatResB\fZ\n" +
	"./proto;pbb\x06proto3"

var (
	file_proto_scheduler_proto_rawDescOnce sync.Once
	file_proto_scheduler_proto_rawDescData []byte
)

func file_proto_scheduler_proto_rawDescGZIP() []byte {
	file_proto_scheduler_proto_rawDescOnce.Do(func() {
		file_proto_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scheduler_proto_rawDesc), len(file_proto_scheduler_proto_rawDesc)))
	})
	return file_proto_scheduler_proto_rawDescData
}

var file_proto_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_scheduler_proto_goTypes = []any{
	(*PrimeReq)(nil),     // 0: PrimeReq
	(*PrimeRes)(nil),     // 1: PrimeRes
	(*HeartbeatReq)(nil), // 2: HeartbeatReq
	(*HeartbeatRes)(nil), // 3: HeartbeatRes
}
var file_proto_scheduler_proto_depIdxs = []int32{
	0, // 0: Scheduler.ListPrimes:input_type -> PrimeReq
	0, // 1: Worker.ListPrimes:input_type -> PrimeReq
	2, // 2: Worker.Heartbeat:input_type -> HeartbeatReq
	1, // 3: Scheduler.ListPrimes:output_type -> PrimeRes
	1, // 4: Worker.ListPrimes:output_type -> PrimeRes
	3, // 5: Worker.Heartbeat:output_type -> HeartbeatRes
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_scheduler_proto_init() }
func file_proto_scheduler_proto_init() {
	if File_proto_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scheduler_proto_rawDesc), len(file_proto_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_scheduler_proto_goTypes,
		DependencyIndexes: file_proto_scheduler_proto_depIdxs,
		MessageInfos:      file_proto_scheduler_proto_msgTypes,
	}.Build()
	File_proto_scheduler_proto = out.File
	file_proto_scheduler_proto_goTypes = nil
	file_proto_scheduler_proto_depIdxs = nil
}
